<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

/**
 * MainSeeder generated automatically from the local 'apa' database.
 */
class MainSeeder extends Seeder
{
    public function run()
    {
        // Disable foreign key checks to allow truncating
        $this->db->query('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate tables in reverse dependency order
        $tablesToTruncate = ['revisi', 'izin', 'riwayat', 'distribusi', 'dokumen', 'unit', 'kategori', 'users'];
        foreach ($tablesToTruncate as $table) {
            $this->db->table($table)->truncate();
        }

        // Enable foreign key checks
        $this->db->query('SET FOREIGN_KEY_CHECKS=1;');

        // 1. Seed Users
        $usersData = [
            [
                'id' => 4,
                'username' => 'NamekianP',
                'nama_lengkap' => 'Namekian',
                'email' => 'Namekiany@gmail.com',
                'password' => '$2y$10$91VY32aAxNvTmB1XTVtBi.4dC2Mn1BwnqlPqHTQoS0ZTJkEZgK5f2',
                'role' => 'admin',
                'created_at' => '2026-05-20 11:48:59',
                'updated_at' => '2026-06-22 19:13:11',
            ],
            [
                'id' => 5,
                'username' => 'admin',
                'nama_lengkap' => 'Administrator Utama',
                'email' => 'admin@example.com',
                'password' => '$2y$10$7tz.HL68fr0Njgv4DlErjO8aNalUN2FuqRPOCgbf0ficy4s3vYVwq',
                'role' => 'admin',
                'created_at' => '2026-05-26 01:52:59',
                'updated_at' => '2026-05-26 01:52:59',
            ],
            [
                'id' => 6,
                'username' => 'petugas',
                'nama_lengkap' => 'Petugas Arsip',
                'email' => 'petugas@example.com',
                'password' => '$2y$10$cqnnQ99WMafTDSYV7R45V.1NtV4nSYDept4Bgqt6ML0TNOPqzomV6',
                'role' => 'karyawan',
                'created_at' => '2026-05-26 01:52:59',
                'updated_at' => '2026-05-26 01:52:59',
            ],
            [
                'id' => 8,
                'username' => 'farel',
                'nama_lengkap' => 'farel',
                'email' => 'farel@gmail.com',
                'password' => '$2y$10$wprOqCFYvo4oVLZDUBEO8e/USmYVSS6TaBTvMMPPURCZS80x0egce',
                'role' => 'karyawan',
                'created_at' => '2026-06-22 19:13:59',
                'updated_at' => '2026-06-25 03:08:42',
            ],
        ];
        if (!empty($usersData)) {
            $this->db->table('users')->insertBatch($usersData);
        }

        // 2. Seed Kategori
        $kategoriData = [
            [
                'id' => 1,
                'nama_kategori' => 'Surat Keputusan (SK)',
                'created_at' => '2026-06-13 05:30:07',
                'updated_at' => '2026-06-13 05:30:07',
            ],
            [
                'id' => 2,
                'nama_kategori' => 'SOP (Standard Operating Procedure)',
                'created_at' => '2026-06-16 05:30:07',
                'updated_at' => '2026-06-16 05:30:07',
            ],
            [
                'id' => 3,
                'nama_kategori' => 'Surat Masuk',
                'created_at' => '2026-06-19 05:30:07',
                'updated_at' => '2026-06-19 05:30:07',
            ],
            [
                'id' => 4,
                'nama_kategori' => 'Surat Keluar',
                'created_at' => '2026-06-22 05:30:07',
                'updated_at' => '2026-06-22 05:30:07',
            ],
            [
                'id' => 5,
                'nama_kategori' => 'Laporan',
                'created_at' => '2026-06-24 05:30:07',
                'updated_at' => '2026-06-24 05:30:07',
            ],
            [
                'id' => 6,
                'nama_kategori' => 'Proposal',
                'created_at' => '2026-06-26 05:30:07',
                'updated_at' => '2026-06-26 05:30:07',
            ],
            [
                'id' => 7,
                'nama_kategori' => 'Formulir',
                'created_at' => '2026-06-28 05:30:07',
                'updated_at' => '2026-06-28 05:30:07',
            ],
        ];
        if (!empty($kategoriData)) {
            $this->db->table('kategori')->insertBatch($kategoriData);
        }

        // 3. Seed Unit
        $unitData = [
            [
                'id' => 1,
                'nama_unit' => 'HRD / Personalia',
                'created_at' => '2026-06-18 05:30:07',
                'updated_at' => '2026-06-18 05:30:07',
            ],
            [
                'id' => 2,
                'nama_unit' => 'Finance / Keuangan',
                'created_at' => '2026-06-20 05:30:07',
                'updated_at' => '2026-06-20 05:30:07',
            ],
            [
                'id' => 3,
                'nama_unit' => 'IT / Teknologi',
                'created_at' => '2026-06-22 05:30:07',
                'updated_at' => '2026-06-22 05:30:07',
            ],
            [
                'id' => 4,
                'nama_unit' => 'Marketing / Pemasaran',
                'created_at' => '2026-06-24 05:30:07',
                'updated_at' => '2026-06-24 05:30:07',
            ],
            [
                'id' => 5,
                'nama_unit' => 'Operations / Operasional',
                'created_at' => '2026-06-26 05:30:07',
                'updated_at' => '2026-06-26 05:30:07',
            ],
            [
                'id' => 6,
                'nama_unit' => 'Legal / Hukum',
                'created_at' => '2026-06-28 05:30:07',
                'updated_at' => '2026-06-28 05:30:07',
            ],
        ];
        if (!empty($unitData)) {
            $this->db->table('unit')->insertBatch($unitData);
        }

        // 4. Seed Dokumen
        $dokumenData = [
            [
                'id' => 1,
                'judul' => 'Laporan Pencapaian Target Q1 2026',
                'deskripsi' => 'Panduan lengkap mengenai tata cara dan prosedur standar operasi yang harus dipatuhi oleh seluruh karyawan divisi terkait.',
                'tanggal' => '2026-04-27',
                'file_dokumen' => '1777299014_88913c5d120f294fefc8.pdf',
                'kategori_id' => 5,
                'unit_id' => 2,
                'ukuran_file' => 152045,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-04-27 14:10:14',
                'updated_at' => '2026-04-27 14:10:14',
            ],
            [
                'id' => 2,
                'judul' => 'Surat Keputusan Pengangkatan Karyawan Tetap',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'tanggal' => '2026-05-19',
                'file_dokumen' => '1779157176_0ecc88f77402323c2ed8.pdf',
                'kategori_id' => 1,
                'unit_id' => 5,
                'ukuran_file' => 3858490,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-05-19 02:19:35',
                'updated_at' => '2026-05-19 02:19:35',
            ],
            [
                'id' => 3,
                'judul' => 'SOP Penggunaan Inventaris Kantor',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti.',
                'tanggal' => '2026-05-19',
                'file_dokumen' => '1779157519_176f0e16df4ee387eee3.pdf',
                'kategori_id' => 2,
                'unit_id' => 2,
                'ukuran_file' => 3858490,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-05-19 02:25:19',
                'updated_at' => '2026-05-19 02:25:19',
            ],
            [
                'id' => 4,
                'judul' => 'Proposal Kegiatan Ulang Tahun Perusahaan',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru.',
                'tanggal' => '2026-05-19',
                'file_dokumen' => '1779192059_a0b55e9af8bc47ce0fca.pdf',
                'kategori_id' => 6,
                'unit_id' => 1,
                'ukuran_file' => 3673115,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-05-19 12:00:59',
                'updated_at' => '2026-05-19 12:00:59',
            ],
            [
                'id' => 5,
                'judul' => 'Laporan Keuangan Bulanan Mei',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'tanggal' => '2026-05-26',
                'file_dokumen' => '1779757612_fb2e5591359a1c7a83cd.pdf',
                'kategori_id' => 5,
                'unit_id' => 3,
                'ukuran_file' => 251518,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-05-26 01:06:52',
                'updated_at' => '2026-05-26 01:06:52',
            ],
            [
                'id' => 6,
                'judul' => 'Surat Edaran Libur Nasional',
                'deskripsi' => 'Rencana anggaran dan kegiatan yang akan dilaksanakan dalam waktu dekat. Membutuhkan persetujuan dari dewan direksi.',
                'tanggal' => '2026-05-26',
                'file_dokumen' => '1779759037_aa04976f0640c225ecab.csv',
                'kategori_id' => 5,
                'unit_id' => 2,
                'ukuran_file' => 22484,
                'ekstensi_file' => 'csv',
                'created_at' => '2026-05-26 01:30:37',
                'updated_at' => '2026-05-26 01:30:37',
            ],
            [
                'id' => 7,
                'judul' => 'Formulir Pengajuan Cuti Tahunan',
                'deskripsi' => 'Panduan lengkap mengenai tata cara dan prosedur standar operasi yang harus dipatuhi oleh seluruh karyawan divisi terkait.',
                'tanggal' => '2026-05-26',
                'file_dokumen' => '1779760501_015f24b2358b2f8d4e70.pdf',
                'kategori_id' => 7,
                'unit_id' => 2,
                'ukuran_file' => 2045038,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-05-26 01:55:01',
                'updated_at' => '2026-05-26 01:55:01',
            ],
            [
                'id' => 8,
                'judul' => 'Dokumentasi Sistem Keamanan Jaringan fja;slkjfa;ldsk',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti. hhha;lsjdfa;sldk',
                'tanggal' => '2026-05-26',
                'file_dokumen' => '1782654635_312b6c7969dc6ac632b8.pdf',
                'kategori_id' => 7,
                'unit_id' => 6,
                'ukuran_file' => 251518,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-05-26 01:55:21',
                'updated_at' => '2026-06-28 13:52:11',
            ],
            [
                'id' => 9,
                'judul' => 'Laporan Audit Internal Tahunan',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru.',
                'tanggal' => '2026-05-26',
                'file_dokumen' => '1779760631_a68702340d6c54ca3d0f.docx',
                'kategori_id' => 5,
                'unit_id' => 3,
                'ukuran_file' => 10815,
                'ekstensi_file' => 'docx',
                'created_at' => '2026-05-26 01:57:11',
                'updated_at' => '2026-05-26 01:57:11',
            ],
            [
                'id' => 10,
                'judul' => 'Proposal Anggaran Kuartal ke-3',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru.',
                'tanggal' => '2026-06-08',
                'file_dokumen' => '1780944999_a1050a29b0d78b2bdfc7.pdf',
                'kategori_id' => 6,
                'unit_id' => 3,
                'ukuran_file' => 7460015,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-08 18:56:39',
                'updated_at' => '2026-06-08 18:56:39',
            ],
            [
                'id' => 11,
                'judul' => 'Analisis Kinerja Operasional Perusahaan petugas',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru. petugas',
                'tanggal' => '2026-06-08',
                'file_dokumen' => '1782650759_fda68f01f0801d690dff.pdf',
                'kategori_id' => 7,
                'unit_id' => 2,
                'ukuran_file' => 2203215,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-08 18:57:04',
                'updated_at' => '2026-06-28 13:42:20',
            ],
            [
                'id' => 12,
                'judul' => 'Rencana Aksi Strategis IT 2026',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'tanggal' => '2026-06-08',
                'file_dokumen' => '1780945389_5655c7678a9eaa2da302.pdf',
                'kategori_id' => 2,
                'unit_id' => 6,
                'ukuran_file' => 2203215,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-08 19:03:09',
                'updated_at' => '2026-06-08 19:03:09',
            ],
            [
                'id' => 13,
                'judul' => 'Kebijakan Keamanan Data Pengguna',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'tanggal' => '2026-06-08',
                'file_dokumen' => '1780945491_ee017cb5f2a232db7eb3.pdf',
                'kategori_id' => 7,
                'unit_id' => 1,
                'ukuran_file' => 368420,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-08 19:04:50',
                'updated_at' => '2026-06-08 19:04:50',
            ],
            [
                'id' => 14,
                'judul' => 'Panduan Kerja Work from Home',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'tanggal' => '2026-06-22',
                'file_dokumen' => '1782142620_fcb245392baea36ff45b.pdf',
                'kategori_id' => 2,
                'unit_id' => 3,
                'ukuran_file' => 4194477,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-22 15:37:00',
                'updated_at' => '2026-06-22 15:37:00',
            ],
            [
                'id' => 15,
                'judul' => 'Formulir Klaim Karyawan',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru.',
                'tanggal' => '2026-06-22',
                'file_dokumen' => '1782151390_986b257887c50a3a1d1d.pdf',
                'kategori_id' => 7,
                'unit_id' => 5,
                'ukuran_file' => 2203215,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-22 18:03:10',
                'updated_at' => '2026-06-22 18:03:10',
            ],
            [
                'id' => 16,
                'judul' => 'Laporan Penjualan Kuartalan',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru.',
                'tanggal' => '2026-06-22',
                'file_dokumen' => '1782154557_1f1d720737adb684e9c5.pdf',
                'kategori_id' => 5,
                'unit_id' => 4,
                'ukuran_file' => 2203215,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-22 18:55:57',
                'updated_at' => '2026-06-22 18:55:57',
            ],
            [
                'id' => 17,
                'judul' => 'Memorandum Kesepahaman Kerja Sama',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'tanggal' => '2026-06-22',
                'file_dokumen' => '1782154740_680343f00fb97ae92eed.pdf',
                'kategori_id' => 3,
                'unit_id' => 4,
                'ukuran_file' => 3858490,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-22 18:58:59',
                'updated_at' => '2026-06-22 18:58:59',
            ],
            [
                'id' => 18,
                'judul' => 'Surat Panggilan Wawancara Kerja farel 333',
                'deskripsi' => 'Rencana anggaran dan kegiatan yang akan dilaksanakan dalam waktu dekat. Membutuhkan persetujuan dari dewan direksi. farell 333',
                'tanggal' => '2026-06-22',
                'file_dokumen' => '1782654365_a02f1ad211dad6efe0be.docx',
                'kategori_id' => 7,
                'unit_id' => 6,
                'ukuran_file' => 3237251,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-22 19:31:04',
                'updated_at' => '2026-06-28 13:47:49',
            ],
            [
                'id' => 19,
                'judul' => 'SOP Mitigasi Bencana Kantor',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti.',
                'tanggal' => '2026-06-22',
                'file_dokumen' => '1782157102_515904b852621c4963d4.pdf',
                'kategori_id' => 2,
                'unit_id' => 4,
                'ukuran_file' => 3237251,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-22 19:38:22',
                'updated_at' => '2026-06-22 19:38:22',
            ],
            [
                'id' => 20,
                'judul' => 'Laporan Tahunan CSR Perusahaan',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti.',
                'tanggal' => '2026-06-22',
                'file_dokumen' => '1782158581_4b3cb02a9e2d5dbf5d08.pdf',
                'kategori_id' => 5,
                'unit_id' => 3,
                'ukuran_file' => 7460015,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-22 20:03:00',
                'updated_at' => '2026-06-22 20:03:00',
            ],
            [
                'id' => 21,
                'judul' => 'Laporan Pencapaian Target Q1 2026',
                'deskripsi' => 'Panduan lengkap mengenai tata cara dan prosedur standar operasi yang harus dipatuhi oleh seluruh karyawan divisi terkait.',
                'tanggal' => '2026-06-25',
                'file_dokumen' => '1782356579_2e01b98d296097aa9da8.docx',
                'kategori_id' => 5,
                'unit_id' => 4,
                'ukuran_file' => 4417082,
                'ekstensi_file' => 'docx',
                'created_at' => '2026-06-25 03:02:59',
                'updated_at' => '2026-06-25 03:02:59',
            ],
            [
                'id' => 22,
                'judul' => 'Surat Keputusan Pengangkatan Karyawan Tetap',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru.',
                'tanggal' => '2026-06-25',
                'file_dokumen' => '1782359977_0bf60e396b328bca7332.pdf',
                'kategori_id' => 1,
                'unit_id' => 3,
                'ukuran_file' => 17235441,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-25 03:59:37',
                'updated_at' => '2026-06-25 03:59:37',
            ],
            [
                'id' => 23,
                'judul' => 'SOP Penggunaan Inventaris Kantor',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'tanggal' => '2026-06-25',
                'file_dokumen' => '1782361451_d4b165e689521273d5bf.pdf',
                'kategori_id' => 2,
                'unit_id' => 3,
                'ukuran_file' => 32287,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-25 04:24:11',
                'updated_at' => '2026-06-25 04:24:11',
            ],
            [
                'id' => 24,
                'judul' => 'Proposal Kegiatan Ulang Tahun Perusahaan',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti.',
                'tanggal' => '2026-06-25',
                'file_dokumen' => '1782361563_11ed363496f8f8b45ae7.docx',
                'kategori_id' => 6,
                'unit_id' => 2,
                'ukuran_file' => 21932,
                'ekstensi_file' => 'docx',
                'created_at' => '2026-06-25 04:26:03',
                'updated_at' => '2026-06-25 04:26:03',
            ],
            [
                'id' => 25,
                'judul' => 'Laporan Keuangan Bulanan Mei',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti.',
                'tanggal' => '2026-06-25',
                'file_dokumen' => '1782362054_ad37f3baee16be5c25e9.pdf',
                'kategori_id' => 5,
                'unit_id' => 6,
                'ukuran_file' => 393693,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-25 04:34:14',
                'updated_at' => '2026-06-25 04:34:14',
            ],
            [
                'id' => 26,
                'judul' => 'Surat Edaran Libur Nasional',
                'deskripsi' => 'Rencana anggaran dan kegiatan yang akan dilaksanakan dalam waktu dekat. Membutuhkan persetujuan dari dewan direksi.',
                'tanggal' => '2026-06-25',
                'file_dokumen' => '1782363433_8019abe485998710d6ff.docx',
                'kategori_id' => 1,
                'unit_id' => 3,
                'ukuran_file' => 10082063,
                'ekstensi_file' => 'docx',
                'created_at' => '2026-06-25 04:57:13',
                'updated_at' => '2026-06-25 04:57:13',
            ],
            [
                'id' => 27,
                'judul' => 'Formulir Pengajuan Cuti Tahunan',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'tanggal' => '2026-06-26',
                'file_dokumen' => '1782464347_c0f117b1af74153ac50d.pdf',
                'kategori_id' => 7,
                'unit_id' => 4,
                'ukuran_file' => 17235441,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-06-26 08:59:07',
                'updated_at' => '2026-06-26 08:59:07',
            ],
            [
                'id' => 28,
                'judul' => 'Dokumentasi Sistem Keamanan Jaringan',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'tanggal' => '2026-06-28',
                'file_dokumen' => '1782646726_7c6f54e003a8acec4027.pdf',
                'kategori_id' => 3,
                'unit_id' => 4,
                'ukuran_file' => 10082063,
                'ekstensi_file' => 'docx',
                'created_at' => '2026-06-28 05:17:19',
                'updated_at' => '2026-06-28 11:39:02',
            ],
            [
                'id' => 29,
                'judul' => 'Sk Pegawai 2026',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru.',
                'tanggal' => '2026-04-27',
                'file_dokumen' => 'sk_pegawai_2026.pdf',
                'kategori_id' => 1,
                'unit_id' => 2,
                'ukuran_file' => 152045,
                'ekstensi_file' => 'pdf',
                'created_at' => '2026-04-27 14:10:14',
                'updated_at' => '2026-04-27 14:10:14',
            ],
        ];
        if (!empty($dokumenData)) {
            $this->db->table('dokumen')->insertBatch($dokumenData);
        }

        // 5. Seed Distribusi
        $distribusiData = [
            [
                'id' => 6,
                'dokumen_id' => 11,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 11:09:02',
                'updated_at' => '2026-06-28 11:11:43',
            ],
            [
                'id' => 7,
                'dokumen_id' => 11,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 11:14:38',
                'updated_at' => '2026-06-28 11:16:36',
            ],
            [
                'id' => 8,
                'dokumen_id' => 8,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 11:23:30',
                'updated_at' => '2026-06-28 11:24:28',
            ],
            [
                'id' => 9,
                'dokumen_id' => 28,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 11:38:04',
                'updated_at' => '2026-06-28 11:38:46',
            ],
            [
                'id' => 10,
                'dokumen_id' => 8,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 11:40:23',
                'updated_at' => '2026-06-28 11:41:20',
            ],
            [
                'id' => 11,
                'dokumen_id' => 11,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 11:43:03',
                'updated_at' => '2026-06-28 11:43:50',
            ],
            [
                'id' => 12,
                'dokumen_id' => 8,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 11:45:39',
                'updated_at' => '2026-06-28 11:46:42',
            ],
            [
                'id' => 13,
                'dokumen_id' => 8,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-04',
                'tanggal_kembali' => '2026-06-26',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 11:50:40',
                'updated_at' => '2026-06-28 13:34:40',
            ],
            [
                'id' => 14,
                'dokumen_id' => 8,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-13',
                'tanggal_kembali' => '2026-06-25',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:00:43',
                'updated_at' => '2026-06-28 13:49:04',
            ],
            [
                'id' => 15,
                'dokumen_id' => 28,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-03',
                'tanggal_kembali' => '2026-06-20',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:02:27',
                'updated_at' => '2026-06-28 12:04:42',
            ],
            [
                'id' => 16,
                'dokumen_id' => 28,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:03:56',
                'updated_at' => '2026-06-28 12:31:01',
            ],
            [
                'id' => 17,
                'dokumen_id' => 11,
                'user_id' => 6,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:11:50',
                'updated_at' => '2026-06-28 12:18:25',
            ],
            [
                'id' => 18,
                'dokumen_id' => 11,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:11:58',
                'updated_at' => '2026-06-28 12:12:30',
            ],
            [
                'id' => 19,
                'dokumen_id' => 28,
                'user_id' => 6,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:25:35',
                'updated_at' => '2026-06-28 12:30:49',
            ],
            [
                'id' => 21,
                'dokumen_id' => 11,
                'user_id' => 6,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:35:25',
                'updated_at' => '2026-06-28 12:35:42',
            ],
            [
                'id' => 22,
                'dokumen_id' => 11,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:37:03',
                'updated_at' => '2026-06-28 12:38:43',
            ],
            [
                'id' => 23,
                'dokumen_id' => 11,
                'user_id' => 6,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:37:09',
                'updated_at' => '2026-06-28 12:39:20',
            ],
            [
                'id' => 24,
                'dokumen_id' => 11,
                'user_id' => 6,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:47:10',
                'updated_at' => '2026-06-28 12:49:15',
            ],
            [
                'id' => 25,
                'dokumen_id' => 11,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 12:47:17',
                'updated_at' => '2026-06-28 12:48:27',
            ],
            [
                'id' => 27,
                'dokumen_id' => 20,
                'user_id' => 6,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-06-30',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 13:20:34',
                'updated_at' => '2026-06-28 13:37:29',
            ],
            [
                'id' => 28,
                'dokumen_id' => 20,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 13:24:53',
                'updated_at' => '2026-06-28 13:34:49',
            ],
            [
                'id' => 31,
                'dokumen_id' => 18,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => null,
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 13:42:59',
                'updated_at' => '2026-06-28 13:46:05',
            ],
            [
                'id' => 32,
                'dokumen_id' => 18,
                'user_id' => 6,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => null,
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 13:43:10',
                'updated_at' => '2026-06-28 13:46:53',
            ],
            [
                'id' => 33,
                'dokumen_id' => 11,
                'user_id' => 6,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-02',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 13:44:56',
                'updated_at' => '2026-06-28 13:50:04',
            ],
            [
                'id' => 34,
                'dokumen_id' => 8,
                'user_id' => 8,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 13:49:04',
                'updated_at' => '2026-06-28 13:51:19',
            ],
            [
                'id' => 35,
                'dokumen_id' => 8,
                'user_id' => 6,
                'tanggal_pinjam' => '2026-06-28',
                'tanggal_kembali' => '2026-07-05',
                'status' => 'Dikembalikan',
                'created_at' => '2026-06-28 13:49:17',
                'updated_at' => '2026-06-28 13:50:35',
            ],
        ];
        if (!empty($distribusiData)) {
            $this->db->table('distribusi')->insertBatch($distribusiData);
        }

        // 6. Seed Riwayat
        $riwayatData = [
            [
                'id' => 21,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan" oleh farel',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 22,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Tolak Izin',
                'keterangan' => 'Menolak izin akses dokumen "Analisis Kinerja Operasional Perusahaan" untuk karyawan farel dengan alasan: "kamu gajelas coba kamu jelaskan administrasi apa yang kamu maksud dan kamu kerja bagian apa " oleh admin',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 23,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan" oleh farel',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 24,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 25,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan farel mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 26,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan" oleh farel',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 27,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 28,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 29,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Penolakan Perubahan',
                'keterangan' => 'Perubahan dokumen ditolak oleh Admin. Pesan: ',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 30,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan" oleh farel',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 31,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 32,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 33,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 8 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 34,
                'dokumen_id' => 28,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan" oleh farel',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 35,
                'dokumen_id' => 28,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 36,
                'dokumen_id' => 28,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 37,
                'dokumen_id' => 28,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 8 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 38,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan" oleh farel',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 39,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 40,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 41,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Penolakan Perubahan',
                'keterangan' => 'Perubahan dokumen ditolak oleh Admin. Pesan: ',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 42,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan" oleh farel',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 43,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 44,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 45,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Penolakan Perubahan',
                'keterangan' => 'Perubahan dokumen ditolak oleh Admin. Pesan: ',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 46,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan" oleh farel',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 47,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 48,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 49,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 8 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 50,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Distribusi Dokumen',
                'keterangan' => 'Dokumen dipinjamkan/didistribusikan ke user ID: 8',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 51,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" oleh farel',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 52,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Tolak Izin',
                'keterangan' => 'Menolak izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" untuk karyawan farel dengan alasan: "ga ah" oleh admin',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 53,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" oleh farel',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 54,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Tolak Izin',
                'keterangan' => 'Menolak izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" untuk karyawan farel dengan alasan: "gaboleh" oleh admin',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 55,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Distribusi Dokumen',
                'keterangan' => 'Dokumen dipinjamkan/didistribusikan ke user ID: 8',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 56,
                'dokumen_id' => 28,
                'user_id' => 5,
                'aksi' => 'Distribusi Dokumen',
                'keterangan' => 'Dokumen dipinjamkan/didistribusikan ke user ID: 8',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 57,
                'dokumen_id' => 28,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan" oleh farel',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 58,
                'dokumen_id' => 28,
                'user_id' => 5,
                'aksi' => 'Tolak Izin',
                'keterangan' => 'Menolak izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan" untuk karyawan farel dengan alasan: "ga mau aku badmood
" oleh admin',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 59,
                'dokumen_id' => 28,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan" oleh farel',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 60,
                'dokumen_id' => 28,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 61,
                'dokumen_id' => 28,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 62,
                'dokumen_id' => 28,
                'user_id' => 5,
                'aksi' => 'Penolakan Perubahan',
                'keterangan' => 'Perubahan dokumen ditolak oleh Admin. Pesan: ',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 63,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan" oleh petugas',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 64,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan" oleh farel',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 65,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan" untuk karyawan petugas oleh admin',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 66,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 67,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan farel mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 68,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 69,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Penolakan Perubahan',
                'keterangan' => 'Perubahan dokumen ditolak oleh Admin. Pesan: ',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 70,
                'dokumen_id' => 28,
                'user_id' => 6,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan" oleh petugas',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 71,
                'dokumen_id' => 28,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan" untuk karyawan petugas oleh admin',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 72,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan farel mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 73,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 74,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Penolakan Perubahan',
                'keterangan' => 'Perubahan dokumen ditolak oleh Admin. Pesan: ',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 75,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 76,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Penolakan Perubahan',
                'keterangan' => 'Perubahan dokumen ditolak oleh Admin. Pesan: gajelas lu',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 77,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan petugas mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 78,
                'dokumen_id' => 28,
                'user_id' => 6,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan petugas mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 79,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan farel mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 80,
                'dokumen_id' => 28,
                'user_id' => 8,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan farel mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 81,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" oleh farel',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 82,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 83,
                'dokumen_id' => 28,
                'user_id' => 6,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan petugas mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 84,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan" oleh petugas',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 85,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan" untuk karyawan petugas oleh admin',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 86,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan petugas mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 87,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan" oleh petugas',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 88,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan" oleh farel',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 89,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 90,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan" untuk karyawan petugas oleh admin',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 91,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 92,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 93,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 6 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 94,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Penolakan Perubahan',
                'keterangan' => 'Sistem menolak otomatis perubahan dari karyawan 8. Pesan: Revisi ditolak otomatis karena pengajuan revisi lain untuk dokumen ini telah disetujui.',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 95,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan petugas" oleh petugas',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 96,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-26 13:00:34',
            ],
            [
                'id' => 97,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Analisis Kinerja Operasional Perusahaan petugas" oleh farel',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 98,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan petugas" untuk karyawan petugas oleh admin',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 99,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Analisis Kinerja Operasional Perusahaan petugas" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-23 13:00:34',
            ],
            [
                'id' => 100,
                'dokumen_id' => 11,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-24 13:00:34',
            ],
            [
                'id' => 101,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-25 13:00:34',
            ],
            [
                'id' => 102,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 6 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-28 13:00:34',
            ],
            [
                'id' => 103,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 8 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-27 13:00:34',
            ],
            [
                'id' => 104,
                'dokumen_id' => 20,
                'user_id' => 5,
                'aksi' => 'Distribusi Dokumen',
                'keterangan' => 'Dokumen dipinjamkan/didistribusikan ke user ID: 6',
                'created_at' => '2026-06-28 13:12:55',
            ],
            [
                'id' => 105,
                'dokumen_id' => 20,
                'user_id' => 5,
                'aksi' => 'Distribusi Dokumen',
                'keterangan' => 'Dokumen dipinjamkan/didistribusikan ke user ID: 6',
                'created_at' => '2026-06-28 13:20:34',
            ],
            [
                'id' => 106,
                'dokumen_id' => 20,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Laporan Tahunan CSR Perusahaan" oleh farel',
                'created_at' => '2026-06-28 13:24:38',
            ],
            [
                'id' => 107,
                'dokumen_id' => 20,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Laporan Tahunan CSR Perusahaan" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-28 13:24:53',
            ],
            [
                'id' => 108,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" oleh farel',
                'created_at' => '2026-06-28 13:26:55',
            ],
            [
                'id' => 109,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-28 13:27:38',
            ],
            [
                'id' => 110,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" oleh farel',
                'created_at' => '2026-06-28 13:28:08',
            ],
            [
                'id' => 111,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-28 13:28:20',
            ],
            [
                'id' => 112,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan farel mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-28 13:34:40',
            ],
            [
                'id' => 113,
                'dokumen_id' => 20,
                'user_id' => 8,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan farel mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-28 13:34:49',
            ],
            [
                'id' => 114,
                'dokumen_id' => 20,
                'user_id' => 8,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan farel mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-28 13:36:18',
            ],
            [
                'id' => 115,
                'dokumen_id' => 20,
                'user_id' => 6,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan petugas mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-28 13:37:29',
            ],
            [
                'id' => 116,
                'dokumen_id' => 8,
                'user_id' => 6,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" oleh petugas',
                'created_at' => '2026-06-28 13:38:32',
            ],
            [
                'id' => 117,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 8 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-28 13:42:20',
            ],
            [
                'id' => 118,
                'dokumen_id' => 18,
                'user_id' => 5,
                'aksi' => 'Distribusi Dokumen',
                'keterangan' => 'Dokumen dipinjamkan/didistribusikan ke user ID: 8',
                'created_at' => '2026-06-28 13:42:59',
            ],
            [
                'id' => 119,
                'dokumen_id' => 18,
                'user_id' => 5,
                'aksi' => 'Distribusi Dokumen',
                'keterangan' => 'Dokumen dipinjamkan/didistribusikan ke user ID: 6',
                'created_at' => '2026-06-28 13:43:10',
            ],
            [
                'id' => 120,
                'dokumen_id' => 11,
                'user_id' => 5,
                'aksi' => 'Distribusi Dokumen',
                'keterangan' => 'Dokumen dipinjamkan/didistribusikan ke user ID: 6',
                'created_at' => '2026-06-28 13:44:56',
            ],
            [
                'id' => 121,
                'dokumen_id' => 18,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-28 13:46:05',
            ],
            [
                'id' => 122,
                'dokumen_id' => 18,
                'user_id' => 6,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-28 13:46:53',
            ],
            [
                'id' => 123,
                'dokumen_id' => 18,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 6 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-28 13:47:13',
            ],
            [
                'id' => 124,
                'dokumen_id' => 18,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 8 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-28 13:47:49',
            ],
            [
                'id' => 125,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Izin',
                'keterangan' => 'Mengajukan permohonan izin akses untuk dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" oleh farel',
                'created_at' => '2026-06-28 13:48:30',
            ],
            [
                'id' => 126,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" untuk karyawan farel oleh admin',
                'created_at' => '2026-06-28 13:49:04',
            ],
            [
                'id' => 127,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Setujui Izin',
                'keterangan' => 'Menyetujui izin akses dokumen "Dokumentasi Sistem Keamanan Jaringan hhhh" untuk karyawan petugas oleh admin',
                'created_at' => '2026-06-28 13:49:17',
            ],
            [
                'id' => 128,
                'dokumen_id' => 11,
                'user_id' => 6,
                'aksi' => 'Kembalikan Dokumen',
                'keterangan' => 'Karyawan petugas mengembalikan dokumen tanpa usulan revisi',
                'created_at' => '2026-06-28 13:50:04',
            ],
            [
                'id' => 129,
                'dokumen_id' => 8,
                'user_id' => 6,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-28 13:50:35',
            ],
            [
                'id' => 130,
                'dokumen_id' => 8,
                'user_id' => 8,
                'aksi' => 'Ajukan Revisi',
                'keterangan' => 'Mengajukan draft perubahan dokumen',
                'created_at' => '2026-06-28 13:51:19',
            ],
            [
                'id' => 131,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 8 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-28 13:51:55',
            ],
            [
                'id' => 132,
                'dokumen_id' => 8,
                'user_id' => 5,
                'aksi' => 'Persetujuan Perubahan',
                'keterangan' => 'Perubahan dari karyawan 6 telah disetujui dan diterapkan.',
                'created_at' => '2026-06-28 13:52:11',
            ],
        ];
        if (!empty($riwayatData)) {
            // Bulk insert in chunks to avoid query size limits
            $chunks = array_chunk($riwayatData, 50);
            foreach ($chunks as $chunk) {
                $this->db->table('riwayat')->insertBatch($chunk);
            }
        }

        // 7. Seed Izin
        $izinData = [
            [
                'id' => 12,
                'user_id' => 8,
                'dokumen_id' => 11,
                'pesan' => 'ini farel 2',
                'pesan_admin' => null,
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 12:46:46',
                'created_at' => '2026-06-28 11:04:35',
                'updated_at' => '2026-06-28 12:48:27',
            ],
            [
                'id' => 13,
                'user_id' => 8,
                'dokumen_id' => 8,
                'pesan' => 'ini lagi',
                'pesan_admin' => null,
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 13:48:30',
                'created_at' => '2026-06-28 11:23:03',
                'updated_at' => '2026-06-28 13:51:19',
            ],
            [
                'id' => 14,
                'user_id' => 8,
                'dokumen_id' => 28,
                'pesan' => 'yaelah bang plis lahh',
                'pesan_admin' => null,
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 12:03:46',
                'created_at' => '2026-06-28 11:37:44',
                'updated_at' => '2026-06-28 12:04:42',
            ],
            [
                'id' => 15,
                'user_id' => 6,
                'dokumen_id' => 11,
                'pesan' => 'lagi petugas',
                'pesan_admin' => 'Langsung diizinkan admin',
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 13:44:56',
                'created_at' => '2026-06-28 12:10:21',
                'updated_at' => '2026-06-28 13:50:04',
            ],
            [
                'id' => 16,
                'user_id' => 6,
                'dokumen_id' => 28,
                'pesan' => 'p',
                'pesan_admin' => null,
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 12:25:20',
                'created_at' => '2026-06-28 12:25:20',
                'updated_at' => '2026-06-28 12:30:49',
            ],
            [
                'id' => 17,
                'user_id' => 6,
                'dokumen_id' => 20,
                'pesan' => 'Langsung diizinkan admin',
                'pesan_admin' => 'Langsung diizinkan admin',
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 13:20:34',
                'created_at' => '2026-06-28 13:20:34',
                'updated_at' => '2026-06-28 13:37:29',
            ],
            [
                'id' => 18,
                'user_id' => 8,
                'dokumen_id' => 20,
                'pesan' => 'bang saya juga',
                'pesan_admin' => null,
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 13:24:38',
                'created_at' => '2026-06-28 13:24:38',
                'updated_at' => '2026-06-28 13:34:49',
            ],
            [
                'id' => 19,
                'user_id' => 6,
                'dokumen_id' => 8,
                'pesan' => 'ini',
                'pesan_admin' => null,
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 13:38:32',
                'created_at' => '2026-06-28 13:38:32',
                'updated_at' => '2026-06-28 13:50:35',
            ],
            [
                'id' => 20,
                'user_id' => 8,
                'dokumen_id' => 18,
                'pesan' => 'Langsung diizinkan admin',
                'pesan_admin' => 'Langsung diizinkan admin',
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 13:42:59',
                'created_at' => '2026-06-28 13:42:59',
                'updated_at' => '2026-06-28 13:46:05',
            ],
            [
                'id' => 21,
                'user_id' => 6,
                'dokumen_id' => 18,
                'pesan' => 'Langsung diizinkan admin',
                'pesan_admin' => 'Langsung diizinkan admin',
                'status_izin' => 'Selesai',
                'tgl_pengajuan' => '2026-06-28 13:43:10',
                'created_at' => '2026-06-28 13:43:10',
                'updated_at' => '2026-06-28 13:46:53',
            ],
        ];
        if (!empty($izinData)) {
            $this->db->table('izin')->insertBatch($izinData);
        }

        // 8. Seed Revisi
        $revisiData = [
            [
                'id' => 3,
                'dokumen_id' => 11,
                'user_id' => 8,
                'judul' => 'Analisis Kinerja Operasional Perusahaan bla bla bla',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru bla bla bla',
                'pesan_revisi' => null,
                'tanggal' => '2026-06-08',
                'kategori_id' => 7,
                'unit_id' => 2,
                'file_dokumen' => '1782645396_ba87bc12afc5e4b98476.pdf',
                'status_revisi' => 'Ditolak',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 11:16:36',
                'updated_at' => '2026-06-28 11:20:30',
            ],
            [
                'id' => 4,
                'dokumen_id' => 8,
                'user_id' => 8,
                'judul' => 'Dokumentasi Sistem Keamanan Jaringan',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti.',
                'pesan_revisi' => 'ini saya ganti bagian apa gitu di file nya terus apa gitu apa dan apa ',
                'tanggal' => '2026-05-26',
                'kategori_id' => 7,
                'unit_id' => 6,
                'file_dokumen' => '1782645868_814f34aa8ec3f836f2f5.docx',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 11:24:28',
                'updated_at' => '2026-06-28 11:36:58',
            ],
            [
                'id' => 5,
                'dokumen_id' => 28,
                'user_id' => 8,
                'judul' => 'Dokumentasi Sistem Keamanan Jaringan',
                'deskripsi' => 'Arsip penting yang merangkum segala aktivitas operasional maupun finansial bulan lalu untuk evaluasi kinerja.',
                'pesan_revisi' => 'revisi dah',
                'tanggal' => '2026-06-28',
                'kategori_id' => 3,
                'unit_id' => 4,
                'file_dokumen' => '1782646726_7c6f54e003a8acec4027.pdf',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 11:38:46',
                'updated_at' => '2026-06-28 11:39:02',
            ],
            [
                'id' => 6,
                'dokumen_id' => 8,
                'user_id' => 8,
                'judul' => 'Dokumentasi Sistem Keamanan Jaringanlaksdjfa;lsd',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti.al;ksdjf;aslkd',
                'pesan_revisi' => 'tolak ajah',
                'tanggal' => '2026-05-26',
                'kategori_id' => 7,
                'unit_id' => 6,
                'file_dokumen' => '1782646880_f2cdcada9fb1c2ac5ed5.pdf',
                'status_revisi' => 'Ditolak',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 11:41:20',
                'updated_at' => '2026-06-28 11:41:49',
            ],
            [
                'id' => 8,
                'dokumen_id' => 8,
                'user_id' => 8,
                'judul' => 'Dokumentasi Sistem Keamanan Jaringan hhhh',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti. hhh',
                'pesan_revisi' => 'Dokumentasi Sistem Keamanan Jaringan \'dklfa;ldskf',
                'tanggal' => '2026-05-26',
                'kategori_id' => 7,
                'unit_id' => 6,
                'file_dokumen' => '1782647202_a9e3f1b4355512af7759.pdf',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 11:46:42',
                'updated_at' => '2026-06-28 11:47:03',
            ],
            [
                'id' => 10,
                'dokumen_id' => 11,
                'user_id' => 6,
                'judul' => 'Analisis Kinerja Operasional Perusahaan',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru.',
                'pesan_revisi' => 'ads;lfkjads;lkfjasd',
                'tanggal' => '2026-06-08',
                'kategori_id' => 7,
                'unit_id' => 2,
                'file_dokumen' => '1782635210_69e14318fbe8d0b80168.docx',
                'status_revisi' => 'Ditolak',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 12:18:25',
                'updated_at' => '2026-06-28 12:18:57',
            ],
            [
                'id' => 11,
                'dokumen_id' => 11,
                'user_id' => 6,
                'judul' => 'Analisis Kinerja Operasional Perusahaan',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru.',
                'pesan_revisi' => 'ganti',
                'tanggal' => '2026-06-08',
                'kategori_id' => 7,
                'unit_id' => 2,
                'file_dokumen' => '1782635210_69e14318fbe8d0b80168.docx',
                'status_revisi' => 'Ditolak',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 12:26:33',
                'updated_at' => '2026-06-28 12:26:53',
            ],
            [
                'id' => 13,
                'dokumen_id' => 11,
                'user_id' => 8,
                'judul' => 'Analisis Kinerja Operasional Perusahaan farel',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru. farel',
                'pesan_revisi' => 'ini farel',
                'tanggal' => '2026-06-08',
                'kategori_id' => 7,
                'unit_id' => 2,
                'file_dokumen' => '1782650323_d39ee7fd9aad3f820729.pdf',
                'status_revisi' => 'Ditolak',
                'pesan_admin' => 'Revisi ditolak otomatis karena pengajuan revisi lain untuk dokumen ini telah disetujui.',
                'created_at' => '2026-06-28 12:38:43',
                'updated_at' => '2026-06-28 12:40:48',
            ],
            [
                'id' => 14,
                'dokumen_id' => 11,
                'user_id' => 6,
                'judul' => 'Analisis Kinerja Operasional Perusahaan petugas',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru. petugas',
                'pesan_revisi' => 'petugas',
                'tanggal' => '2026-06-08',
                'kategori_id' => 7,
                'unit_id' => 2,
                'file_dokumen' => '1782650360_6dd23c52742f6ea61a7a.pdf',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 12:39:20',
                'updated_at' => '2026-06-28 12:40:48',
            ],
            [
                'id' => 15,
                'dokumen_id' => 11,
                'user_id' => 8,
                'judul' => 'Analisis Kinerja Operasional Perusahaan petugas',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru. petugas',
                'pesan_revisi' => 'ini farel 2',
                'tanggal' => '2026-06-08',
                'kategori_id' => 7,
                'unit_id' => 2,
                'file_dokumen' => '1782650759_fda68f01f0801d690dff.pdf',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 12:45:59',
                'updated_at' => '2026-06-28 13:42:20',
            ],
            [
                'id' => 16,
                'dokumen_id' => 11,
                'user_id' => 8,
                'judul' => 'Analisis Kinerja Operasional Perusahaan farel 2',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru. farel 2',
                'pesan_revisi' => 'farel 2',
                'tanggal' => '2026-06-08',
                'kategori_id' => 7,
                'unit_id' => 2,
                'file_dokumen' => '1782650907_68cf5587cfd67e26f66f.pdf',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 12:48:27',
                'updated_at' => '2026-06-28 12:50:24',
            ],
            [
                'id' => 17,
                'dokumen_id' => 11,
                'user_id' => 6,
                'judul' => 'Analisis Kinerja Operasional Perusahaan petugas2',
                'deskripsi' => 'Merupakan dokumen resmi yang disahkan oleh pimpinan perusahaan mengenai kebijakan dan regulasi terbaru. petugas2',
                'pesan_revisi' => 'petugas2',
                'tanggal' => '2026-06-08',
                'kategori_id' => 7,
                'unit_id' => 2,
                'file_dokumen' => '1782650955_fb15d9e7210310a5ca5a.pdf',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 12:49:15',
                'updated_at' => '2026-06-28 12:50:08',
            ],
            [
                'id' => 18,
                'dokumen_id' => 18,
                'user_id' => 8,
                'judul' => 'Surat Panggilan Wawancara Kerja farel 333',
                'deskripsi' => 'Rencana anggaran dan kegiatan yang akan dilaksanakan dalam waktu dekat. Membutuhkan persetujuan dari dewan direksi. farell 333',
                'pesan_revisi' => 'ini farel 333',
                'tanggal' => '2026-06-22',
                'kategori_id' => 7,
                'unit_id' => 6,
                'file_dokumen' => '1782654365_a02f1ad211dad6efe0be.docx',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 13:46:05',
                'updated_at' => '2026-06-28 13:47:49',
            ],
            [
                'id' => 19,
                'dokumen_id' => 18,
                'user_id' => 6,
                'judul' => 'Surat Panggilan Wawancara Kerja ini petugas 33',
                'deskripsi' => 'Rencana anggaran dan kegiatan yang akan dilaksanakan dalam waktu dekat. Membutuhkan persetujuan dari dewan direksi. etugas 333',
                'pesan_revisi' => 'petugas333',
                'tanggal' => '2026-06-22',
                'kategori_id' => 7,
                'unit_id' => 6,
                'file_dokumen' => '1782654413_1223496d0db9ca86ab46.pdf',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 13:46:53',
                'updated_at' => '2026-06-28 13:47:13',
            ],
            [
                'id' => 20,
                'dokumen_id' => 8,
                'user_id' => 6,
                'judul' => 'Dokumentasi Sistem Keamanan Jaringan fja;slkjfa;ldsk',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti. hhha;lsjdfa;sldk',
                'pesan_revisi' => 'laskdf;alskdf',
                'tanggal' => '2026-05-26',
                'kategori_id' => 7,
                'unit_id' => 6,
                'file_dokumen' => '1782654635_312b6c7969dc6ac632b8.pdf',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 13:50:35',
                'updated_at' => '2026-06-28 13:52:11',
            ],
            [
                'id' => 21,
                'dokumen_id' => 8,
                'user_id' => 8,
                'judul' => 'Dokumentasi Sistem Keamanan Jaringan hhhh aku rapi',
                'deskripsi' => 'Dokumen ini berisi detail mengenai pencapaian dan rekapitulasi data selama periode yang ditentukan. Harap dibaca dengan teliti. hhh aku rapi',
                'pesan_revisi' => 'aku rapi',
                'tanggal' => '2026-05-26',
                'kategori_id' => 7,
                'unit_id' => 6,
                'file_dokumen' => '1782654679_507fc8cdfdf24a5d18f0.docx',
                'status_revisi' => 'Disetujui',
                'pesan_admin' => null,
                'created_at' => '2026-06-28 13:51:19',
                'updated_at' => '2026-06-28 13:51:55',
            ],
        ];
        if (!empty($revisiData)) {
            $this->db->table('revisi')->insertBatch($revisiData);
        }
    }
}